apiVersion: v1
kind: Service
metadata:
  name: spring-boot-lazy
  labels:
    name: spring-boot-lazy
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-lazy
  type: LoadBalancer